summary: Password reset
description: This endpoint is used to reset admin 
operationId: "onboardPasswordReset"
requestBody:
  content:
    application/json:
      schema:
        properties:
          old_password:
            type: string
          new_password1:
            type: string
          new_password2:
            type: string
        type: object
  required: true
responses:
  "200":
    description: OK
security:
  - BearerAuth: []
tags:
  - config
