summary: Create connection with data intermediary
description: This endpoint is used to establish connection with data intermediary
operationId: "configCreateConnection"
responses:
  "200":
    content:
      application/json:
        schema:
          $ref: "../definitions/CreateConnectionResponse.yaml"
    description: "OK"
security:
  - BearerAuth: []
tags:
  - config
