summary: Update data source
description: This endpoint is used to update data source
operationId: "configUpdateDataSource"
requestBody:
  content:
    application/json:
      schema:
        properties:
          dataSource:
            type: object
            properties:
              description:
                type: string
              location:
                type: string
              name:
                type: string
              policyUrl:
                type: string
              required:
                - name
                - location
                - description
                - policyUrl
        type: object
  required: true
responses:
  "200":
    content:
      application/json:
        schema:
          properties:
            dataSource:
              $ref: ../definitions/Organisation.yaml
            verification:
              $ref: "../definitions/Verification.yaml"
    description: "Updated the organisation"
security:
  - BearerAuth: []
tags:
  - config
