summary: Update admin
description: This endpoint is used to update admin details
operationId: "configUpdateAdmin"
requestBody:
  content:
    application/json:
      schema:
        properties:
          name:
            type: string
        type: object
  required: true
responses:
  "200":
    description: OK
    content:
      application/json:
        schema:
          $ref: "../definitions/OrganisationAdmin.yaml"
security:
  - BearerAuth: []
tags:
  - config
