summary: Read admin
description: This endpoint is used to read admin details
operationId: "configReadAdmin"
responses:
  "200":
    description: OK
    content:
      application/json:
        schema:
          $ref: "../definitions/OrganisationAdmin.yaml"
security:
  - BearerAuth: []
tags:
  - config
