summary: List connections
description: This endpoint is used to list connections
operationId: "configListConnection"
parameters:
  - $ref: "../parameters/offset.yaml"
  - $ref: "../parameters/limit.yaml"
responses:
  "200":
    description: OK
    content:
      application/json:
        schema:
          type: object
          properties:
            connections:
              type: array
              items:
                $ref: "../definitions/Connection.yaml"
            pagination:
              $ref: "../definitions/Pagination.yaml"
  "400":
    description: bad input parameter
tags:
  - config
security:
- BearerAuth: []