summary: Read verification
description: This endpoint is used to read verification for a data source
operationId: "configReadVerification"
responses:
  "200":
    content:
      application/json:
        schema:
          properties:
            verification:
              $ref: "../definitions/Verification.yaml"
          type: object
    description: OK
security:
  - BearerAuth: []
tags:
  - config
