summary: Delete connection
description: |
  This endpoint is used to delete connection by ID.
operationId: configDeleteConnection
parameters:
  - $ref: "../parameters/path/connectionId.yaml"
responses:
  "204":
    description: OK
  "400":
    description: bad input parameter
security:
  - BearerAuth: []
tags:
  - config
