summary: Read data source
description: This endpoint is used to read the data source details for the organisation admin
operationId: "configReadDataSource"
responses:
  "200":
    content:
      application/json:
        schema:
          properties:
            dataSource:
              $ref: ../definitions/Organisation.yaml
            verification:
              $ref: "../definitions/Verification.yaml"
          type: object
    description: OK
security:
  - BearerAuth: []
tags:
  - config
