# Generated by Django 3.0.7 on 2025-09-03 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverImageUrl', models.CharField(max_length=255)),
                ('logoUrl', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('policyUrl', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('coverImageId', models.UUIDField(blank=True, default=None, null=True)),
                ('logoId', models.UUIDField(blank=True, default=None, null=True)),
                ('owsBaseUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('openApiUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
