# Generated by Django 3.0.7 on 2025-09-03 10:51

import uuid

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationIdentityTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organisationIdentityTemplateName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issuerName", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "issuerLocation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "issuerLogoUrl",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "presentationDefinitionId",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganisationIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "presentationExchangeId",
                    models.CharField(max_length=50, unique=True),
                ),
                ("presentationState", models.CharField(max_length=50)),
                ("isPresentationVerified", models.BooleanField(default=False)),
                ("presentationRecord", jsonfield.fields.JSONField(default=dict)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "organisationId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisation.Organisation",
                    ),
                ),
            ],
        ),
    ]
