# Generated by Django 3.0.7 on 2025-09-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0002_organisationidentity_organisationidentitytemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="accessPointEndpoint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="credentialOfferEndpoint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
