# Generated by Django 3.0.7 on 2025-09-26 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20250916_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sectorName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Organisation Sector',
                'verbose_name_plural': 'Organisation Sectors',
            },
        ),
        migrations.AlterModelOptions(
            name='organisationidentity',
            options={'verbose_name': 'Organisation Identity', 'verbose_name_plural': 'Organisation Identities'},
        ),
        migrations.AlterModelOptions(
            name='organisationidentitytemplate',
            options={'verbose_name': 'Organisation Identity Template', 'verbose_name_plural': 'Organisation Identity Template'},
        ),
    ]
