# Generated by Django 3.0.7 on 2025-09-26 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20250926_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOfConduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdfFile', models.FileField(upload_to='code_of_conduct/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Code of Conduct',
                'verbose_name_plural': 'Code of Conduct',
                'ordering': ['-updatedAt'],
            },
        ),
    ]
