# Generated by Django 3.0.7 on 2025-09-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0005_codeofconduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="codeOfConduct",
            field=models.BooleanField(default=False),
        ),
    ]
