# Generated by Django 4.2.28 on 2026-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_codeofconduct_store_pdf_in_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationidentity',
            name='presentationRecord',
            field=models.JSONField(),
        ),
    ]
