components:
  schemas:
    Organisation:
      $ref: "./definitions/Organisation.yaml"
    PersonalData:
      $ref: "./definitions/PersonalData.yaml"
    DataDisclosureAgreement:
      $ref: "./definitions/DataDisclosureAgreement.yaml"
    DataUsingService:
      $ref: "./definitions/DataUsingService.yaml"
    Proof:
      $ref: "./definitions/Proof.yaml"
    DataSharingRestriction:
      $ref: "./definitions/DataSharingRestriction.yaml"
    DataController:
      $ref: "./definitions/DataController.yaml"
    Pagination:
      $ref: "./definitions/Pagination.yaml"
    Connection:
      $ref: "./definitions/Connection.yaml"
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      description: Access token passed with Bearer prefix in Authorization header
      scheme: bearer
      type: http
info:
  contact:
    email: support@igrant.io
    name: iGrant.io
    url: https://igrant.io
  description: iGrant.io (™) is a Swedish data exchange and verification service provider. It uses self-sovereign identity, verifiable credentials, a digital wallet and solid pod technologies, enabling a new level of interoperability and automating compliance with data regulations in a fully auditable manner.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: Dataspace Portal API documentation
  version: 2024.3.1
openapi: 3.1.0
paths:
  /service/data-disclosure-agreement/:
    get:
      $ref: "./paths/listDataDisclosureAgreement.yaml"
  /config/data-source/:
    get:
      $ref: "./paths/readDataSource.yaml"
    put:
      $ref: "./paths/updateDataSource.yaml"
  /config/data-source/coverimage/:
    get:
      $ref: "./paths/readDataSourceCoverImage.yaml"
    put:
      $ref: "./paths/updateDataSourceCoverImage.yaml"
  /config/data-source/logoimage/:
    get:
      $ref: "./paths/readDataSourceLogoImage.yaml"
    put:
      $ref: "./paths/updateDataSourceLogoImage.yaml"
  /onboard/login/:
    post:
      $ref: "./paths/login.yaml"
  /onboard/register/:
    post:
      $ref: "./paths/register.yaml"
  /onboard/token/refresh/:
    post:
      $ref: "./paths/refreshtoken.yaml"
  /onboard/admin/:
    get:
      $ref: "./paths/readAdmin.yaml"
servers:
  - description: Development server
    url: http://localhost:8000
tags:
  - description: This consists of endpoints available to organisation admins to manage data disclosure agreements and connections.
    name: config
    x-tag-expanded: true
  - description: This consists of endpoints towards data using services to list and connect to data sources, view data disclosure agreements and APIs.
    name: service
    x-tag-expanded: true
  - description: This consists of endpoints towards authentication and authorisation.
    name: onboard
    x-tag-expanded: true
