components:
  schemas:
    Organisation:
      $ref: "./definitions/Organisation.yaml"
    PersonalData:
      $ref: "./definitions/PersonalData.yaml"
    DataDisclosureAgreement:
      $ref: "./definitions/DataDisclosureAgreement.yaml"
    DataUsingService:
      $ref: "./definitions/DataUsingService.yaml"
    Proof:
      $ref: "./definitions/Proof.yaml"
    DataSharingRestriction:
      $ref: "./definitions/DataSharingRestriction.yaml"
    DataController:
      $ref: "./definitions/DataController.yaml"
    Pagination:
      $ref: "./definitions/Pagination.yaml"
    InvitationUrl:
      $ref: "./definitions/InvitationUrl.yaml"
    Connection:
      $ref: "./definitions/Connection.yaml"
    Verification:
      $ref: "./definitions/Verification.yaml"
    Status:
      $ref: "./definitions/Status.yaml"
    ConnectionRecord:
      $ref: "./definitions/ConnectionRecord.yaml"
    CreateConnectionResponse:
      $ref: "./definitions/CreateConnectionResponse.yaml"
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      description: Access token passed with Bearer prefix in Authorization header
      scheme: bearer
      type: http
info:
  contact:
    email: support@igrant.io
    name: iGrant.io
    url: https://igrant.io
  description: iGrant.io (™) is a Swedish data exchange and verification service provider. It uses self-sovereign identity, verifiable credentials, a digital wallet and solid pod technologies, enabling a new level of interoperability and automating compliance with data regulations in a fully auditable manner.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: Dataspace Portal API documentation
  version: 2024.3.1
openapi: 3.1.0
paths:
  /webhook/topic/connections/:
    post:
      $ref: "./paths/createWebhookConnection.yaml"
  /webhook/topic/present_proof/:
    post:
      $ref: "./paths/createWebhookPresentProof.yaml"
  /webhook/topic/published_data_disclosure_agreement/:
    post:
      $ref: "./paths/createWebhookDataDisclosureAgreement.yaml"
  /service/data-source/{dataSourceId}/coverimage:
    get:
      $ref: "./paths/serviceReadDataSourceCoverImage.yaml"
  /service/data-source/{dataSourceId}/logoimage:
    get:
      $ref: "./paths/serviceReadDataSourceLogoImage.yaml"
  /service/data-sources/:
    get:
      $ref: "./paths/serviceListDataSource.yaml"
  /config/verification/templates:
    get:
      $ref: "./paths/configListVerificationTemplate.yaml"
  /config/open-api/url:
    put:
      $ref: "./paths/configUpdateOpenApiUrl.yaml"
  /config/connection/:
    post:
      $ref: "./paths/configCreateConnection.yaml"
  /config/connections/:
    get:
      $ref: "./paths/configListConnection.yaml"
  /config/connection/{connectionId}/:
    delete:
      $ref: "./paths/configDeleteConnection.yaml"
  /config/data-disclosure-agreement/{dataDisclosureAgreementId}/:
    get:
      $ref: "./paths/configReadDataDisclosureAgreement.yaml"
    delete:
      $ref: "./paths/configDeleteDataDisclosureAgreement.yaml"
  /config/data-disclosure-agreement/{dataDisclosureAgreementId}/status/:
    put:
      $ref: "./paths/configUpdateDataDisclosureAgreementStatus.yaml"
  /config/data-disclosure-agreements/:
    get:
      $ref: "./paths/configListDataDisclosureAgreement.yaml"
  /config/data-source/verification/:
    post:
      $ref: "./paths/configCreateVerification.yaml"
    get:
      $ref: "./paths/configReadVerification.yaml"
  /config/data-source/:
    post:
      $ref: "./paths/configCreateDataSource.yaml"
    get:
      $ref: "./paths/configReadDataSource.yaml"
    put:
      $ref: "./paths/configUpdateDataSource.yaml"
  /config/data-source/coverimage/:
    get:
      $ref: "./paths/configReadDataSourceCoverImage.yaml"
    put:
      $ref: "./paths/configUpdateDataSourceCoverImage.yaml"
  /config/data-source/logoimage/:
    get:
      $ref: "./paths/configReadDataSourceLogoImage.yaml"
    put:
      $ref: "./paths/configUpdateDataSourceLogoImage.yaml"
  /config/admin/:
    get:
      $ref: "./paths/configReadAdmin.yaml"
    put:
      $ref: "./paths/configUpdateAdmin.yaml"
  /config/admin/reset-password/:
    post:
      $ref: "./paths/configPasswordReset.yaml"
  /onboard/login/:
    post:
      $ref: "./paths/onboardLogin.yaml"
  /onboard/register/:
    post:
      $ref: "./paths/onboardRegister.yaml"
  /onboard/token/refresh/:
    post:
      $ref: "./paths/onboardRefreshtoken.yaml"
servers:
  - description: Development server
    url: http://localhost:8000
  - description: Live server
    url: https://api.nxd.foundation
tags:
  - description: This consists of endpoints available to organisation admins to manage data disclosure agreements and connections.
    name: config
    x-tag-expanded: true
  - description: This consists of endpoints towards data using services to list and connect to data sources, view data disclosure agreements and APIs.
    name: service
    x-tag-expanded: true
  - description: This consists of endpoints towards authentication and authorisation.
    name: onboard
    x-tag-expanded: true
