# Generated by Django 3.0.7 on 2025-09-03 05:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuth2Clients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("client_secret", models.CharField(max_length=255)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the client", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the client"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_clients",
                        to="organisation.Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth2 Client",
                "verbose_name_plural": "OAuth2 Clients",
                "db_table": "oauth2_clients",
                "ordering": ["-created_at"],
            },
        ),
    ]
