# Generated by Django 3.0.7 on 2025-09-18 04:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20250916_1301'),
        ('oAuth2Clients', '0002_auto_20250903_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationOAuth2Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(help_text='Human-readable name for the client', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the client')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_oauth_clients', to='organisation.Organisation')),
            ],
            options={
                'verbose_name': 'Organisation OAuth2 Client',
                'verbose_name_plural': 'Organisation OAuth2 Clients',
                'db_table': 'organisation_oauth2_clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='organisationoauth2clients',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='uniq_client_name'),
        ),
    ]
