# Generated by Django 3.0.7 on 2025-09-18 12:41

import uuid

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "data_disclosure_agreement",
            "0006_datadisclosureagreementtemplate_datadisclosureagreementtemplaterevisionid",
        ),
        ("organisation", "0003_auto_20250916_1301"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDisclosureAgreementRecordHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("unsigned", "unsigned"), ("signed", "signed")],
                        default="unsigned",
                        max_length=255,
                    ),
                ),
                (
                    "dataDisclosureAgreementRecord",
                    jsonfield.fields.JSONField(default=dict),
                ),
                ("dataDisclosureAgreementTemplateId", models.CharField(max_length=255)),
                (
                    "dataDisclosureAgreementTemplateRevisionId",
                    models.CharField(max_length=255),
                ),
                ("dataDisclosureAgreementRecordId", models.CharField(max_length=255)),
                ("optIn", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "dataDisclosureAgreementTemplate",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_disclosure_agreement.DataDisclosureAgreementTemplate",
                    ),
                ),
                (
                    "organisationId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisation.Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Disclosure Agreement Record History",
                "verbose_name_plural": "Data Disclosure Agreement Record History",
            },
        ),
        migrations.CreateModel(
            name="DataDisclosureAgreementRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("unsigned", "unsigned"), ("signed", "signed")],
                        default="unsigned",
                        max_length=255,
                    ),
                ),
                (
                    "dataDisclosureAgreementRecord",
                    jsonfield.fields.JSONField(default=dict),
                ),
                ("dataDisclosureAgreementTemplateId", models.CharField(max_length=255)),
                (
                    "dataDisclosureAgreementTemplateRevisionId",
                    models.CharField(max_length=255),
                ),
                ("dataDisclosureAgreementRecordId", models.CharField(max_length=255)),
                ("optIn", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "organisationId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisation.Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Disclosure Agreement Record",
                "verbose_name_plural": "Data Disclosure Agreement Record",
            },
        ),
    ]
