# Generated by Django 4.2.28 on 2026-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_disclosure_agreement_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadisclosureagreementrecord',
            name='dataDisclosureAgreementRecord',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datadisclosureagreementrecordhistory',
            name='dataDisclosureAgreementRecord',
            field=models.JSONField(),
        ),
    ]
