"""
OAuth2 Clients Serializers.

This module provides serializers for managing OAuth2 client credentials
used in machine-to-machine (M2M) authentication within the data space.

Two types of OAuth2 clients are supported:
1. OAuth2Clients - System-generated clients where credentials (client_id
   and client_secret) are auto-generated by the backend during creation.
2. OrganisationOAuth2Clients - Organisation-managed clients where
   credentials are provided by the organisation during registration.

These clients enable secure API authentication using the OAuth2
client_credentials grant type.
"""

from __future__ import annotations

from typing import Any

from rest_framework import serializers

from .models import OAuth2Clients, OrganisationOAuth2Clients


class OAuth2ClientsSerializer(serializers.ModelSerializer):  # type: ignore[type-arg]
    """
    Serializer for OAuth2Clients read operations and listing.

    Provides a complete view of OAuth2 client information including
    the associated organisation name. Used for listing clients and
    retrieving client details.

    Note: The organisation field is write-only to prevent circular
    references in responses, while organisation_name provides a
    human-readable reference.
    """

    # Nested field to display the organisation's name without exposing
    # the full organisation object in the response
    organisation_name = serializers.CharField(
        source="organisation.name", read_only=True
    )

    class Meta:
        model = OAuth2Clients
        fields = [
            "id",
            "client_id",
            "client_secret",
            "name",
            "description",
            "organisation",
            "organisation_name",
            "is_active",
            "created_at",
            "updated_at",
        ]
        # Credentials and timestamps are system-managed and cannot be
        # modified through the API
        read_only_fields = [
            "id",
            "client_id",
            "client_secret",
            "created_at",
            "updated_at",
        ]
        # Organisation is accepted on write but not included in responses
        # to avoid redundancy with organisation_name
        extra_kwargs = {"organisation": {"write_only": True}}


class OAuth2ClientsCreateSerializer(serializers.ModelSerializer):  # type: ignore[type-arg]
    """
    Serializer for creating new OAuth2 clients.

    Only accepts name and description as input. The client_id and
    client_secret are automatically generated by the model's save
    method, ensuring secure credential generation without user input.
    """

    class Meta:
        model = OAuth2Clients
        # Only allow setting basic metadata; credentials are auto-generated
        fields = ["name", "description"]

    def create(self, validated_data: dict[str, Any]) -> OAuth2Clients:
        """
        Create a new OAuth2 client with auto-generated credentials.

        The model's save method automatically generates a secure
        client_id and client_secret upon creation.
        """
        # The model's save method will auto-generate client_id and client_secret
        return OAuth2Clients.objects.create(**validated_data)


class OAuth2ClientsUpdateSerializer(serializers.ModelSerializer):  # type: ignore[type-arg]
    """
    Serializer for updating existing OAuth2 clients.

    Allows modification of client metadata (name, description) and
    activation status. Credentials (client_id and client_secret)
    cannot be modified after creation to maintain security.
    """

    class Meta:
        model = OAuth2Clients
        # Only allow updating metadata and status; credentials are immutable
        fields = ["name", "description", "is_active"]


class OrganisationOAuth2ClientsSerializer(serializers.ModelSerializer):  # type: ignore[type-arg]
    """
    Serializer for OrganisationOAuth2Clients read operations and listing.

    Similar to OAuth2ClientsSerializer but for organisation-managed
    clients. These clients have credentials provided by the organisation
    rather than being auto-generated by the system.

    Used for listing and retrieving organisation OAuth2 client details.
    """

    # Nested field to display the organisation's name for better readability
    # in API responses without exposing the full organisation object
    organisation_name = serializers.CharField(
        source="organisation.name", read_only=True
    )

    class Meta:
        model = OrganisationOAuth2Clients
        fields = [
            "id",
            "client_id",
            "client_secret",
            "name",
            "description",
            "organisation",
            "organisation_name",
            "is_active",
            "created_at",
            "updated_at",
        ]
        # ID, credentials, and timestamps are protected from modification
        read_only_fields = [
            "id",
            "client_id",
            "client_secret",
            "created_at",
            "updated_at",
        ]
        # Organisation reference is write-only to keep responses clean
        extra_kwargs = {"organisation": {"write_only": True}}


class OrganisationOAuth2ClientsCreateSerializer(serializers.ModelSerializer):  # type: ignore[type-arg]
    """
    Serializer for creating organisation-managed OAuth2 clients.

    Unlike OAuth2ClientsCreateSerializer, this serializer requires
    the organisation to provide their own client_id and client_secret.
    This is useful when organisations need to use pre-existing
    credentials or have specific credential management requirements.
    """

    class Meta:
        model = OrganisationOAuth2Clients
        # Accept both metadata and credentials from the organisation
        fields = ["name", "description", "client_id", "client_secret"]

    def create(self, validated_data: dict[str, Any]) -> OrganisationOAuth2Clients:
        """
        Create a new organisation OAuth2 client with provided credentials.

        Unlike system-generated clients, the credentials are supplied
        by the organisation and stored as-is.
        """
        return OrganisationOAuth2Clients.objects.create(**validated_data)
