# Generated by Django 3.0.7 on 2025-09-16 13:01

import uuid

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisation", "0003_auto_20250916_1301"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareStatementTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "softwareStatementTemplateName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "credentialDefinitionId",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoftwareStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credentialExchangeId", models.CharField(max_length=50, unique=True)),
                ("status", models.CharField(max_length=50)),
                ("credentialHistory", jsonfield.fields.JSONField(default=dict)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "organisationId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisation.Organisation",
                    ),
                ),
            ],
        ),
    ]
