# Generated by Django 4.2.28 on 2026-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_statement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarestatement',
            name='credentialHistory',
            field=models.JSONField(),
        ),
    ]
