# Generated by Django 3.0.7 on 2024-03-27 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverImageUrl', models.CharField(max_length=255)),
                ('logoUrl', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('policyUrl', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('coverImageId', models.UUIDField(blank=True, default=None, null=True)),
                ('logoId', models.UUIDField(blank=True, default=None, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presentationExchangeId', models.CharField(max_length=50, unique=True)),
                ('presentationState', models.CharField(max_length=50)),
                ('presentationRecord', models.CharField(max_length=50)),
                ('dataSourceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.DataSource')),
            ],
        ),
    ]
