# Generated by Django 3.0.7 on 2024-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0002_verificationtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="openApiUrl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
