# Generated by Django 3.0.7 on 2024-04-04 07:25

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_datasource_openapiurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtemplate',
            name='dataAgreementId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='presentationRecord',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
