# Generated by Django 3.0.7 on 2024-04-08 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20240405_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
