# Generated by Django 4.2.28 on 2026-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_datasource_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='presentationRecord',
            field=models.JSONField(),
        ),
    ]
