# Generated by Django 3.0.7 on 2025-09-18 09:07

import uuid

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisation", "0003_auto_20250916_1301"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("b2bConnectionRecord", jsonfield.fields.JSONField(default=dict)),
                ("b2bConnectionId", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "organisationId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisation.Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "B2B Connection",
                "verbose_name_plural": "B2B Connection",
            },
        ),
    ]
