# Generated by Django 4.2.28 on 2026-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bconnection',
            name='b2bConnectionRecord',
            field=models.JSONField(),
        ),
    ]
