# Generated by Django 3.0.7 on 2024-04-02 05:58

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDisclosureAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('templateId', models.CharField(max_length=255)),
                ('templateVersion', models.CharField(max_length=255)),
                ('dataController', jsonfield.fields.JSONField(default=dict)),
                ('agreementPeriod', models.IntegerField()),
                ('dataSharingRestrictions', jsonfield.fields.JSONField(default=dict)),
                ('purpose', models.CharField(max_length=255)),
                ('purposeDescription', models.CharField(max_length=255)),
                ('lawfulBasis', models.CharField(max_length=255)),
                ('personalData', jsonfield.fields.JSONField(blank=True, default=list)),
                ('codeOfConduct', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('listed', 'listed'), ('unlisted', 'unlisted'), ('awaitingForApproval', 'awaitingForApproval'), ('approved', 'approved'), ('rejected', 'rejected')], default='awaitingForApproval', max_length=255)),
                ('revisions', jsonfield.fields.JSONField(blank=True, default=list)),
                ('dataSourceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.DataSource')),
            ],
        ),
    ]
