# Generated by Django 3.0.7 on 2024-04-05 15:38

import uuid

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("config", "0005_auto_20240405_0607"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDisclosureAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=255)),
                ("templateId", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("listed", "listed"),
                            ("unlisted", "unlisted"),
                            ("awaitingForApproval", "awaitingForApproval"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="unlisted",
                        max_length=255,
                    ),
                ),
                (
                    "dataDisclosureAgreementRecord",
                    jsonfield.fields.JSONField(default=dict),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("isLatestVersion", models.BooleanField(default=True)),
                (
                    "dataSourceId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.DataSource",
                    ),
                ),
            ],
        ),
    ]
