# Generated by Django 3.0.7 on 2024-04-03 18:46

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('data_disclosure_agreement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadisclosureagreement',
            old_name='dataController',
            new_name='dataDisclosureAgreementRecord',
        ),
        migrations.RemoveField(
            model_name='datadisclosureagreement',
            name='agreementPeriod',
        ),
        migrations.RemoveField(
            model_name='datadisclosureagreement',
            name='codeOfConduct',
        ),
        migrations.RemoveField(
            model_name='datadisclosureagreement',
            name='dataSharingRestrictions',
        ),
        migrations.RemoveField(
            model_name='datadisclosureagreement',
            name='language',
        ),
        migrations.RemoveField(
            model_name='datadisclosureagreement',
            name='lawfulBasis',
        ),
        migrations.RemoveField(
            model_name='datadisclosureagreement',
            name='personalData',
        ),
        migrations.RemoveField(
            model_name='datadisclosureagreement',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='datadisclosureagreement',
            name='purposeDescription',
        ),
        migrations.RemoveField(
            model_name='datadisclosureagreement',
            name='revisions',
        ),
        migrations.RemoveField(
            model_name='datadisclosureagreement',
            name='templateVersion',
        ),
        migrations.AddField(
            model_name='datadisclosureagreement',
            name='createdAt',
            field=models.IntegerField(default=time.time_ns, editable=False),
        ),
        migrations.AddField(
            model_name='datadisclosureagreement',
            name='isLatestVersion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datadisclosureagreement',
            name='status',
            field=models.CharField(choices=[('listed', 'listed'), ('unlisted', 'unlisted'), ('awaitingForApproval', 'awaitingForApproval'), ('approved', 'approved'), ('rejected', 'rejected')], default='unlisted', max_length=255),
        ),
    ]
