# Generated by Django 3.0.7 on 2024-04-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_disclosure_agreement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadisclosureagreement',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
