# Generated by Django 3.0.7 on 2025-09-03 11:49

import uuid

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0002_organisationidentity_organisationidentitytemplate"),
        ("data_disclosure_agreement", "0002_auto_20250902_0851"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDisclosureAgreementTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=255)),
                ("templateId", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("listed", "listed"),
                            ("unlisted", "unlisted"),
                            ("awaitingForApproval", "awaitingForApproval"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="unlisted",
                        max_length=255,
                    ),
                ),
                (
                    "dataDisclosureAgreementRecord",
                    jsonfield.fields.JSONField(default=dict),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("isLatestVersion", models.BooleanField(default=True)),
                (
                    "organisationId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisation.Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Disclosure Agreement - Manage Listing",
                "verbose_name_plural": "Data Disclosure Agreement - Manage Listing",
            },
        ),
    ]
