# Generated by Django 3.0.7 on 2025-09-17 09:25

import django.db.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_disclosure_agreement", "0004_auto_20250915_0917"),
    ]

    operations = [
        migrations.AddField(
            model_name="datadisclosureagreementtemplate",
            name="dataDisclosureAgreementTemplateRevision",
            field=django.db.models.JSONField(default=dict),
        ),
    ]
