# Generated by Django 3.0.7 on 2025-09-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_disclosure_agreement",
            "0005_datadisclosureagreementtemplate_datadisclosureagreementtemplaterevision",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datadisclosureagreementtemplate",
            name="dataDisclosureAgreementTemplateRevisionId",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
