# Generated by Django 3.0.7 on 2025-09-23 08:49

from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('data_disclosure_agreement', '0006_datadisclosureagreementtemplate_datadisclosureagreementtemplaterevisionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadisclosureagreementtemplate',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE data_disclosure_agreement_datadisclosureagreementtemplate "
                "SET updatedAt = NOW() WHERE updatedAt IS NULL;"
            )
        ),
        migrations.AlterField(
            model_name='datadisclosureagreementtemplate',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]

