# Generated by Django 3.0.7 on 2025-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_disclosure_agreement",
            "0006_datadisclosureagreementtemplate_datadisclosureagreementtemplaterevisionid",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datadisclosureagreementtemplate",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
