# Generated by Django 3.0.7 on 2026-01-05 05:09

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_disclosure_agreement", "0007_datadisclosureagreementtemplate_updatedat"),
    ]

    operations = [
        migrations.AddField(
            model_name="datadisclosureagreementtemplate",
            name="tags",
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
