# Generated by Django 4.2.28 on 2026-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_disclosure_agreement', '0008_add_tags_to_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadisclosureagreement',
            name='dataDisclosureAgreementRecord',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datadisclosureagreementtemplate',
            name='dataDisclosureAgreementRecord',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datadisclosureagreementtemplate',
            name='dataDisclosureAgreementTemplateRevision',
            field=models.JSONField(),
        ),
    ]
