# Generated by Django 3.0.7 on 2024-03-28 09:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("connectionId", models.UUIDField()),
                ("state", models.CharField(max_length=20)),
                ("myDid", models.CharField(max_length=50)),
                ("theirLabel", models.CharField(max_length=255)),
                ("routingState", models.CharField(max_length=20)),
                ("invitationKey", models.CharField(max_length=255)),
                ("invitationMode", models.CharField(max_length=20)),
                ("initiator", models.CharField(max_length=20)),
                ("updatedAt", models.DateTimeField()),
                ("accept", models.CharField(max_length=20)),
                ("requestId", models.UUIDField()),
                ("createdAt", models.DateTimeField()),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                ("errorMsg", models.TextField(blank=True, null=True)),
                (
                    "inboundConnectionId",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("theirDid", models.CharField(blank=True, max_length=50, null=True)),
                ("theirRole", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "dataSourceId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.DataSource",
                    ),
                ),
            ],
        ),
    ]
