# Generated by Django 3.0.7 on 2024-04-02 07:13

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connection", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connection",
            old_name="accept",
            new_name="connectionState",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="alias",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="createdAt",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="errorMsg",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="inboundConnectionId",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="initiator",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="invitationKey",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="invitationMode",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="myDid",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="requestId",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="routingState",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="state",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="theirDid",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="theirLabel",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="theirRole",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="updatedAt",
        ),
        migrations.AddField(
            model_name="connection",
            name="connectionRecord",
            field=jsonfield.fields.JSONField(default=dict, max_length=512),
        ),
        migrations.AlterField(
            model_name="connection",
            name="connectionId",
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
