# Generated by Django 4.2.28 on 2026-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_auto_20240402_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connectionRecord',
            field=models.JSONField(max_length=512),
        ),
    ]
