# Generated by Django 4.2.28 on 2026-02-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0004_mfacode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataspaceuser',
            name='is_mfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
